source 'http://rubygems.org'


# The gems that we use to test our stuff
def testing_gems
  gem "bundler", "~> 1.6"
  gem "rake"
  gem "rspec", '~> 3.0.0'
  gem "simplecov"
  gem 'powerpack'
end

# The development (i.e. source code) versions of gems that are (or are needed by) our stuff
def dev_gems
  gem 'task_runner', path: '../task_runner'
  gem 'tef-development', :path => 'gems/tef-development'
end

# The real (i.e. installed on the machine) versions gems that are (or are needed by) our stuff
def test_gems
  gem 'task_runner'
  gem 'tef-development'
end

# Nothing new to see here.
def prod_gems
  test_gems
end

puts "Bundler mode: #{ENV['BUNDLE_MODE']}"
mode = ENV['BUNDLE_MODE']

case mode
  when 'dev'
    testing_gems
    dev_gems
  when 'test', 'prod'
    testing_gems
    test_gems
  when 'prod'
    prod_gems
  else
    raise(ArgumentError, "Unknown bundle mode: #{mode}. Must be one of dev/test/prod.")
end
