require 'bundler/gem_tasks'
require 'rspec/core/rake_task'

namespace 'task_runner' do

  namespace 'rspec' do
    desc 'Run all specifications for the gem'
    RSpec::Core::RakeTask.new(:specs, :command_options) do |t, args|
      t.rspec_opts = "-t ~wip -t ~off "
      t.rspec_opts << args[:command_options] if args[:command_options]
    end
  end

  desc 'Test everything for task_runner'
  task :test_everything, [:command_options] do |_t, args|
    Rake::Task['task_runner:rspec:specs'].invoke(args[:command_options])
  end

  task :default => :test_everything
end
