require 'cucumber/rake/task'
require 'rspec/core/rake_task'

# todo - reduce this duplication
def set_cucumber_options(options)
  ENV['CUCUMBER_OPTS'] = options
end

def combine_options(set_1, set_2)
  set_2 ? "#{set_1} #{set_2}" : set_1
end


namespace 'tef' do
  namespace 'core' do

    namespace 'cucumber' do
      desc 'Run all tests for the core'
      task :tests, [:command_options] do |t, args|
        set_cucumber_options(combine_options('-t ~@wip -t ~@off', args[:command_options]))
      end
      Cucumber::Rake::Task.new(:tests)
    end

    namespace 'rspec' do
      desc 'Run all specifications for the core'
      RSpec::Core::RakeTask.new(:specs, :command_options) do |t, args|
        t.rspec_opts = '--tag ~wip '
        t.rspec_opts << args[:command_options] if args[:command_options]
      end
    end

    desc 'Run everything for the core'
    task :test_everything, [:command_options] do |t, args|
      Rake::Task['tef:core:rspec:specs'].invoke(args[:command_options])
      Rake::Task['tef:core:cucumber:tests'].invoke(args[:command_options])
    end


    task :default => 'tef:core:test_everything'
  end
end
