source 'https://rubygems.org'


# The gems that we use to test our stuff
def testing_gems
  gem 'pry'
  gem 'pry-debugger'
  gem 'rake'
  gem 'rspec', '~> 3.0.0'
  gem 'cucumber'
  gem 'simplecov'
  gem 'database_cleaner'
  gem 'racatt'
end

# The development (i.e. source code) versions of gems that are (or are needed by) our stuff
def dev_gems
  gem 'bunny', '~> 1.4'
  gem 'tiny_tds', '~> 0.6'
  gem 'activerecord', '~> 4.1'
  gem 'activerecord-sqlserver-adapter', '~> 4.1'
  gem 'workers'

  # Dev mode has to explicitly include every needed gem dependency in the project in order to
  # be properly (i.e. recursively) loaded from source by Bundler
  gem 'res_man', git: 'https://github.com/grange-insurance/res_man.git', branch: 'master'
  gem 'tef-core', path: '../tef-core'
  gem 'tef-manager', path: '../tef-manager'
end

# The real (i.e. installed on the machine) versions gems that are (or are needed by) our stuff
def test_gems
  gem 'bunny', '~> 1.4'
  gem 'tiny_tds', '~> 0.6'
  gem 'activerecord', '~> 4.1'
  gem 'activerecord-sqlserver-adapter', '~> 4.1'
  gem 'workers'

  gem 'res_man'
  gem 'tef-core'
  gem 'tef-manager'
end

# Nothing new to see here.
def prod_gems
  test_gems
end

puts "Bundler mode: #{ENV['BUNDLE_MODE']}"
mode = ENV['BUNDLE_MODE']

case mode
  when 'dev'
    testing_gems
    dev_gems
  when 'test', 'prod'
    testing_gems
    test_gems
  when 'prod'
    prod_gems
  else
    raise(ArgumentError, "Unknown bundle mode: #{mode}. Must be one of dev/test/prod.")
end
