require 'racatt'


namespace 'tef' do
  namespace 'keeper' do

    def tef_env
      !ENV['TEF_ENV'].nil? ? ENV['TEF_ENV'].downcase : 'dev'
    end

    def keeper_config
      !ENV['KEEPER_CONFIG'].nil? ? ENV['KEEPER_CONFIG'] : './config'
    end


    Racatt.create_tasks


    task default: :test_everything
  end
end

task default: 'tef:keeper:test_everything'
